[package]
name = "py-strobealign"
version = "0.0.0"
edition = "2024"

[lib]
name = "strobealign"
crate-type = ["cdylib"]

[dependencies]
strobealign = { path = ".." }
pyo3 = { version = "0.27.2", features = ["extension-module"] }
